apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self-management
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    repoURL: https://github.com/wim-vdw/argocd-setup.git
    path: argocd-setup/overlays/prod
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - PruneLast=true
