apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- ../../base
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.13.1/manifests/install.yaml
- argocd-self-management.yaml

patches:
- path: argocd-cm.patch.yaml
- path: argocd-cmd-params-cm.patch.yaml
