apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.14.2/manifests/install.yaml
- argocd-self-management.yaml
- argocd-server-http-ingress.yaml

patches:
- path: argocd-cm.patch.yaml
- path: argocd-cmd-params-cm.patch.yaml
- target:
    kind: Deployment
    name: .*
  patch: |-
    - op: add
      path: /spec/template/spec/imagePullSecrets #/-
      value: [{ name: jfrog-artifactory-secret }]
- target:
    kind: Statefulset
    name: .*
  patch: |-
    - op: add
      path: /spec/template/spec/imagePullSecrets #/-
      value: [{ name: jfrog-artifactory-secret }]
- target:
    kind: DaemonSet
    name: .*
  patch: |-
    - op: add
      path: /spec/template/spec/imagePullSecrets #/-
      value: [{ name: jfrog-artifactory-secret }]

images:
  - name: redis
    newName: oneretailhackaton.jfrog.io/virtual-docker/redis